const ACTIONS = {
  LOGIN_USER: 'LOGIN_USER',
  EXPENSES_ADD: 'EXPENSES_ADD',
  EXPENSES_REMOVE: 'EXPENSES_REMOVE',
  EXPENSES_EDIT: 'EXPENSES_EDIT',
  CURRENCY_ADD: 'ACTIONS.CURRENCY_ADD',
};

export default ACTIONS;
